(define (cbrt x)
  (define (good-enough? guess prev-guess)
    (< (abs (- guess prev-guess)) 0.00001))
  (define (improve guess)
    (average (/ (+ (/ x (square guess))
                   (* guess 2))
                3)
             guess))
  (define (try guess prev-guess)
    (if (good-enough? guess prev-guess)
        guess
        (try (improve guess) guess)))
  (try 1.0 x))

(displayln (cbrt 27))
(displayln (cbrt 0.001))
(displayln (cbrt 1000000))
(displayln (cbrt 117649))
(exit)
